const listings = [
  {
    id: 1,
    title: "Girls PG near Bandra Station",
    location: "Mumbai",
    area: "Bandra",
    price: 9000,
    gender: "Girls",
    type: "PG",
    rating: 4.5,
    amenities: ["WiFi", "Food", "AC", "Laundry"],
    image: "https://asset-cdn.stanzaliving.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1585230160/Website/CMS-Uploads/j6nmhp7foszuo6leeoqq.jpg",
    image: "https://asset-cdn.stanzaliving.com/stanza-living/image/upload/f_auto,q_auto,w_600/e_improve/e_sharpen:10/e_saturation:10/v1669097135/Website/CMS-Uploads/JWS08128_29_30-2_wyfujs.jpg",
  },
  {
    id: 2,
    title: "Boys Flat in Andheri East",
    location: "Mumbai",
    area: "Andheri",
    price: 13000,
    gender: "Boys",
    type: "Flat",
    rating: 4.2,
    amenities: ["WiFi", "Parking", "Kitchen"],
    image: "https://via.placeholder.com/300",
    description: "Spacious 2BHK flat close to metro and colleges."
  },
  {
    id: 3,
    title: "Affordable PG for Girls",
    location: "Pune",
    area: "Kothrud",
    price: 7000,
    gender: "Girls",
    type: "PG",
    rating: 4.1,
    amenities: ["WiFi", "Food"],
    image: "https://via.placeholder.com/300",
    description: "Budget-friendly PG with peaceful environment."
  },
  {
    id: 4,
    title: "Student Flat near FC Road",
    location: "Pune",
    area: "Shivajinagar",
    price: 11000,
    gender: "Boys",
    type: "Flat",
    rating: 4.6,
    amenities: ["WiFi", "AC", "Parking"],
    image: "https://via.placeholder.com/300",
    description: "Fully furnished flat near major colleges."
  },
  {
    id: 5,
    title: "Cozy Girls PG in South Delhi",
    location: "Delhi",
    area: "Saket",
    price: 9500,
    gender: "Girls",
    type: "PG",
    rating: 4.4,
    amenities: ["WiFi", "Food", "Laundry"],
    image: "https://via.placeholder.com/300",
    description: "Clean and secure PG in prime Delhi location."
  },
  {
    id: 6,
    title: "Modern Boys Flat in Dwarka",
    location: "Delhi",
    area: "Dwarka",
    price: 12500,
    gender: "Boys",
    type: "Flat",
    rating: 4.3,
    amenities: ["WiFi", "Kitchen", "Parking"],
    image: "https://via.placeholder.com/300",
    description: "Comfortable flat with all modern facilities."
  },
  {
    id: 7,
    title: "Girls PG near Salt Lake",
    location: "Kolkata",
    area: "Salt Lake",
    price: 8000,
    gender: "Girls",
    type: "PG",
    rating: 4.2,
    amenities: ["WiFi", "Food", "AC"],
    image: "https://via.placeholder.com/300",
    description: "Perfect PG for students near IT hub."
  },
  {
    id: 8,
    title: "Boys Flat in New Town",
    location: "Kolkata",
    area: "New Town",
    price: 10500,
    gender: "Boys",
    type: "Flat",
    rating: 4.5,
    amenities: ["WiFi", "Parking", "Gym"],
    image: "https://via.placeholder.com/300",
    description: "Spacious flat with modern amenities."
  },
  {
    id: 9,
    title: "Peaceful PG in Siliguri",
    location: "Siliguri",
    area: "Pradhan Nagar",
    price: 6000,
    gender: "Girls",
    type: "PG",
    rating: 4.0,
    amenities: ["WiFi", "Food"],
    image: "https://via.placeholder.com/300",
    description: "Quiet and comfortable stay for students."
  },
  {
    id: 10,
    title: "Budget Flat in Siliguri",
    location: "Siliguri",
    area: "Matigara",
    price: 8500,
    gender: "Boys",
    type: "Flat",
    rating: 4.1,
    amenities: ["WiFi", "Kitchen"],
    image: "https://via.placeholder.com/300",
    description: "Affordable flat with basic facilities."
  },
  {
    id: 11,
    title: "Village Style PG Stay",
    location: "Aramdanga",
    area: "Green Fields",
    price: 4000,
    gender: "Girls",
    type: "PG",
    rating: 4.6,
    amenities: ["Fresh Food", "Nature View", "Peaceful"],
    image: "https://via.placeholder.com/300",
    description: "Beautiful village stay with fresh air and greenery."
  },
  {
    id: 12,
    title: "Simple Student Flat",
    location: "Aramdanga",
    area: "Lake Side",
    price: 5000,
    gender: "Boys",
    type: "Flat",
    rating: 4.3,
    amenities: ["Kitchen", "Nature View"],
    image: "https://via.placeholder.com/300",
    description: "Minimal and peaceful living space near lake."
  },
  {
    id: 13,
    title: "Luxury PG in Mumbai",
    location: "Mumbai",
    area: "Powai",
    price: 15000,
    gender: "Girls",
    type: "PG",
    rating: 4.8,
    amenities: ["WiFi", "AC", "Food", "Gym"],
    image: "https://via.placeholder.com/300",
    description: "Premium PG with luxury facilities."
  },
  {
    id: 14,
    title: "Affordable Boys PG",
    location: "Delhi",
    area: "Laxmi Nagar",
    price: 6500,
    gender: "Boys",
    type: "PG",
    rating: 4.0,
    amenities: ["WiFi", "Food"],
    image: "https://via.placeholder.com/300",
    description: "Best for students preparing for exams."
  },
  {
    id: 15,
    title: "Student Friendly Flat",
    location: "Kolkata",
    area: "Garia",
    price: 9000,
    gender: "Girls",
    type: "Flat",
    rating: 4.4,
    amenities: ["WiFi", "Kitchen", "Parking"],
    image: "https://via.placeholder.com/300",
    description: "Well-connected flat with all basic facilities."
  }
];